//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 

using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml;
using System.Xml.Serialization;

namespace BPMNET.Bpmn
{

    [GeneratedCode("xsd", "4.0.30319.1")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace = "http://www.omg.org/spec/BPMN/20100524/MODEL")]
    [XmlRoot("messageEventDefinition", Namespace = "http://www.omg.org/spec/BPMN/20100524/MODEL", IsNullable = false)]
    public partial class tMessageEventDefinition : tEventDefinition
    {

        private XmlQualifiedName operationRefField;

        private XmlQualifiedName messageRefField;

            public XmlQualifiedName operationRef
        {
            get
            {
                return operationRefField;
            }
            set
            {
                operationRefField = value;
            }
        }

            [XmlAttribute()]
        public XmlQualifiedName messageRef
        {
            get
            {
                return messageRefField;
            }
            set
            {
                messageRefField = value;
            }
        }
    }
}